/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';


declare global {

  namespace StencilComponents {
    interface StellarAccordion {
      'label': string;
      'name': string;
      'open': boolean;
      'refresh': () => void;
      'tight': boolean;
    }
  }

  interface HTMLStellarAccordionElement extends StencilComponents.StellarAccordion, HTMLStencilElement {}

  var HTMLStellarAccordionElement: {
    prototype: HTMLStellarAccordionElement;
    new (): HTMLStellarAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-accordion': HTMLStellarAccordionElement;
  }
  interface ElementTagNameMap {
    'stellar-accordion': HTMLStellarAccordionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-accordion': JSXElements.StellarAccordionAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarAccordionAttributes extends HTMLAttributes {
      'label'?: string;
      'name'?: string;
      'open'?: boolean;
      'tight'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarAnimateText {
      'method': string|"glitch"|"lettering"|"weight"|"fade";
    }
  }

  interface HTMLStellarAnimateTextElement extends StencilComponents.StellarAnimateText, HTMLStencilElement {}

  var HTMLStellarAnimateTextElement: {
    prototype: HTMLStellarAnimateTextElement;
    new (): HTMLStellarAnimateTextElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-animate-text': HTMLStellarAnimateTextElement;
  }
  interface ElementTagNameMap {
    'stellar-animate-text': HTMLStellarAnimateTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-animate-text': JSXElements.StellarAnimateTextAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarAnimateTextAttributes extends HTMLAttributes {
      'method'?: string|"glitch"|"lettering"|"weight"|"fade";
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarAssetLibrary {

    }
  }

  interface HTMLStellarAssetLibraryElement extends StencilComponents.StellarAssetLibrary, HTMLStencilElement {}

  var HTMLStellarAssetLibraryElement: {
    prototype: HTMLStellarAssetLibraryElement;
    new (): HTMLStellarAssetLibraryElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-asset-library': HTMLStellarAssetLibraryElement;
  }
  interface ElementTagNameMap {
    'stellar-asset-library': HTMLStellarAssetLibraryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-asset-library': JSXElements.StellarAssetLibraryAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarAssetLibraryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarAsset {
      'align': string;
      'block': boolean;
      'language': string;
      'name': string;
      'src': string;
    }
  }

  interface HTMLStellarAssetElement extends StencilComponents.StellarAsset, HTMLStencilElement {}

  var HTMLStellarAssetElement: {
    prototype: HTMLStellarAssetElement;
    new (): HTMLStellarAssetElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-asset': HTMLStellarAssetElement;
  }
  interface ElementTagNameMap {
    'stellar-asset': HTMLStellarAssetElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-asset': JSXElements.StellarAssetAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarAssetAttributes extends HTMLAttributes {
      'align'?: string;
      'block'?: boolean;
      'language'?: string;
      'name'?: string;
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarAvatar {
      'color': string;
      'initials': string;
      'name': string;
      'notooltip': boolean;
      'processing': boolean;
      'shape': "circle"|"square"|"rectangle"|"diamond"|"hexagon"|"star"|"message";
      'size': string;
      'src': string;
    }
  }

  interface HTMLStellarAvatarElement extends StencilComponents.StellarAvatar, HTMLStencilElement {}

  var HTMLStellarAvatarElement: {
    prototype: HTMLStellarAvatarElement;
    new (): HTMLStellarAvatarElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-avatar': HTMLStellarAvatarElement;
  }
  interface ElementTagNameMap {
    'stellar-avatar': HTMLStellarAvatarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-avatar': JSXElements.StellarAvatarAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarAvatarAttributes extends HTMLAttributes {
      'color'?: string;
      'initials'?: string;
      'name'?: string;
      'notooltip'?: boolean;
      'processing'?: boolean;
      'shape'?: "circle"|"square"|"rectangle"|"diamond"|"hexagon"|"star"|"message";
      'size'?: string;
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarBlur {
      'horizontal': number;
      'setBlurFilter': () => void;
      'vertical': number;
    }
  }

  interface HTMLStellarBlurElement extends StencilComponents.StellarBlur, HTMLStencilElement {}

  var HTMLStellarBlurElement: {
    prototype: HTMLStellarBlurElement;
    new (): HTMLStellarBlurElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-blur': HTMLStellarBlurElement;
  }
  interface ElementTagNameMap {
    'stellar-blur': HTMLStellarBlurElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-blur': JSXElements.StellarBlurAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarBlurAttributes extends HTMLAttributes {
      'horizontal'?: number;
      'vertical'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarBreadcrumb {
      'color': string;
      'disabled': boolean;
      'href': string;
      'target': string;
      'title': string;
    }
  }

  interface HTMLStellarBreadcrumbElement extends StencilComponents.StellarBreadcrumb, HTMLStencilElement {}

  var HTMLStellarBreadcrumbElement: {
    prototype: HTMLStellarBreadcrumbElement;
    new (): HTMLStellarBreadcrumbElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-breadcrumb': HTMLStellarBreadcrumbElement;
  }
  interface ElementTagNameMap {
    'stellar-breadcrumb': HTMLStellarBreadcrumbElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-breadcrumb': JSXElements.StellarBreadcrumbAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarBreadcrumbAttributes extends HTMLAttributes {
      'color'?: string;
      'disabled'?: boolean;
      'href'?: string;
      'target'?: string;
      'title'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarBreadcrumbs {
      'color': string;
      'description': string;
      'home': string;
      'icon': string;
      'icon_size': number;
      'icon_src': string;
      'title': string;
    }
  }

  interface HTMLStellarBreadcrumbsElement extends StencilComponents.StellarBreadcrumbs, HTMLStencilElement {}

  var HTMLStellarBreadcrumbsElement: {
    prototype: HTMLStellarBreadcrumbsElement;
    new (): HTMLStellarBreadcrumbsElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-breadcrumbs': HTMLStellarBreadcrumbsElement;
  }
  interface ElementTagNameMap {
    'stellar-breadcrumbs': HTMLStellarBreadcrumbsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-breadcrumbs': JSXElements.StellarBreadcrumbsAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarBreadcrumbsAttributes extends HTMLAttributes {
      'color'?: string;
      'description'?: string;
      'home'?: string;
      'icon'?: string;
      'icon_size'?: number;
      'icon_src'?: string;
      'title'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarButton {
      /**
       * Sets the button or link as an active state.
       */
      'active': boolean;
      /**
       * Sets the button or link to render at full width to the parent.
       */
      'block': boolean;
      /**
       * Sets the button or link to provide the affordance of a dangerous action.
       */
      'danger': boolean;
      /**
       * Sets the button or link as disabled and not-interactable.
       */
      'disabled': boolean;
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'for': string;
      'ghost': boolean;
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'href': string;
      /**
       * Sets the button or link as a button with only an icon.
       */
      'icon': boolean;
      /**
       * Sets the button or link as an outlined button.
       */
      'invert': boolean;
      /**
       * Sets accessibility options on the buttons
       */
      'label': string;
      /**
       * Sets the name on the button if the button is an input. Allows the button to act as an item in a form.
       */
      'name': string;
      /**
       * Sets the button or link as an outlined button.
       */
      'outline': boolean;
      /**
       * Sets the padding inside of the button. Can be small, medium, or large.
       */
      'padding': string|"small"|"medium"|"large";
      /**
       * Sets the button or link to render as a pill.
       */
      'pill': boolean;
      /**
       * Sets the button or link as processing when clicked.
       */
      'processable': boolean;
      /**
       * Sets the size of the button. Can be tiny, small, medium, or large.
       */
      'size': string|"tiny"|"small"|"medium"|"large";
      /**
       * Allows the button to render for different tags.
       */
      'tag': "button"|"submit"|"link"|"span";
      /**
       * Sets the target on the anchor tag if the button is a link.
       */
      'target': string;
      /**
       * Sets the value on the button if the button is an input.
       */
      'value': string;
    }
  }

  interface HTMLStellarButtonElement extends StencilComponents.StellarButton, HTMLStencilElement {}

  var HTMLStellarButtonElement: {
    prototype: HTMLStellarButtonElement;
    new (): HTMLStellarButtonElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-button': HTMLStellarButtonElement;
  }
  interface ElementTagNameMap {
    'stellar-button': HTMLStellarButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-button': JSXElements.StellarButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarButtonAttributes extends HTMLAttributes {
      /**
       * Sets the button or link as an active state.
       */
      'active'?: boolean;
      /**
       * Sets the button or link to render at full width to the parent.
       */
      'block'?: boolean;
      /**
       * Sets the button or link to provide the affordance of a dangerous action.
       */
      'danger'?: boolean;
      /**
       * Sets the button or link as disabled and not-interactable.
       */
      'disabled'?: boolean;
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'for'?: string;
      'ghost'?: boolean;
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'href'?: string;
      /**
       * Sets the button or link as a button with only an icon.
       */
      'icon'?: boolean;
      /**
       * Sets the button or link as an outlined button.
       */
      'invert'?: boolean;
      /**
       * Sets accessibility options on the buttons
       */
      'label'?: string;
      /**
       * Sets the name on the button if the button is an input. Allows the button to act as an item in a form.
       */
      'name'?: string;
      /**
       * Sets the button or link as an outlined button.
       */
      'outline'?: boolean;
      /**
       * Sets the padding inside of the button. Can be small, medium, or large.
       */
      'padding'?: string|"small"|"medium"|"large";
      /**
       * Sets the button or link to render as a pill.
       */
      'pill'?: boolean;
      /**
       * Sets the button or link as processing when clicked.
       */
      'processable'?: boolean;
      /**
       * Sets the size of the button. Can be tiny, small, medium, or large.
       */
      'size'?: string|"tiny"|"small"|"medium"|"large";
      /**
       * Allows the button to render for different tags.
       */
      'tag'?: "button"|"submit"|"link"|"span";
      /**
       * Sets the target on the anchor tag if the button is a link.
       */
      'target'?: string;
      /**
       * Sets the value on the button if the button is an input.
       */
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarCallout {
      'type': "alert"|"error"|"info"|"success";
    }
  }

  interface HTMLStellarCalloutElement extends StencilComponents.StellarCallout, HTMLStencilElement {}

  var HTMLStellarCalloutElement: {
    prototype: HTMLStellarCalloutElement;
    new (): HTMLStellarCalloutElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-callout': HTMLStellarCalloutElement;
  }
  interface ElementTagNameMap {
    'stellar-callout': HTMLStellarCalloutElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-callout': JSXElements.StellarCalloutAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCalloutAttributes extends HTMLAttributes {
      'type'?: "alert"|"error"|"info"|"success";
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarCard {
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'for': string;
      /**
       * Sets the href if the card is a link.
       */
      'href': string;
      /**
       * Sets the name if the card is a button.
       */
      'name': string;
      /**
       * Sets the padding inside of the button. Can be small, medium, or large.
       */
      'padding': string|"small"|"medium"|"large";
      /**
       * Renders a shadow on the card
       */
      'shadow': string|"light"|"medium"|"heavy";
      /**
       * Sets the element to render the card as - an anchor tag, a button, or a div.
       */
      'tag': "a"|"button"|"div";
      'transition': boolean;
      /**
       * Sets the value if the card is a button.
       */
      'value': string;
    }
  }

  interface HTMLStellarCardElement extends StencilComponents.StellarCard, HTMLStencilElement {}

  var HTMLStellarCardElement: {
    prototype: HTMLStellarCardElement;
    new (): HTMLStellarCardElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-card': HTMLStellarCardElement;
  }
  interface ElementTagNameMap {
    'stellar-card': HTMLStellarCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-card': JSXElements.StellarCardAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCardAttributes extends HTMLAttributes {
      /**
       * Sets the href on the anchor tag if the button is a link.
       */
      'for'?: string;
      /**
       * Sets the href if the card is a link.
       */
      'href'?: string;
      /**
       * Sets the name if the card is a button.
       */
      'name'?: string;
      /**
       * Sets the padding inside of the button. Can be small, medium, or large.
       */
      'padding'?: string|"small"|"medium"|"large";
      /**
       * Renders a shadow on the card
       */
      'shadow'?: string|"light"|"medium"|"heavy";
      /**
       * Sets the element to render the card as - an anchor tag, a button, or a div.
       */
      'tag'?: "a"|"button"|"div";
      'transition'?: boolean;
      /**
       * Sets the value if the card is a button.
       */
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarChart {
      'data': (data: any) => void;
      'for': string;
      'options': (newOptions: any) => void;
      'random': boolean;
      'refresh': () => void;
      'remote': string;
      'series': (data: any) => void;
      'type': string;
    }
  }

  interface HTMLStellarChartElement extends StencilComponents.StellarChart, HTMLStencilElement {}

  var HTMLStellarChartElement: {
    prototype: HTMLStellarChartElement;
    new (): HTMLStellarChartElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-chart': HTMLStellarChartElement;
  }
  interface ElementTagNameMap {
    'stellar-chart': HTMLStellarChartElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-chart': JSXElements.StellarChartAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarChartAttributes extends HTMLAttributes {
      'for'?: string;
      'random'?: boolean;
      'remote'?: string;
      'type'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarCodeBlock {
      'codeString': string;
      'copy': boolean;
      'language': string;
      'result': () => any;
      'simple': boolean;
    }
  }

  interface HTMLStellarCodeBlockElement extends StencilComponents.StellarCodeBlock, HTMLStencilElement {}

  var HTMLStellarCodeBlockElement: {
    prototype: HTMLStellarCodeBlockElement;
    new (): HTMLStellarCodeBlockElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-code-block': HTMLStellarCodeBlockElement;
  }
  interface ElementTagNameMap {
    'stellar-code-block': HTMLStellarCodeBlockElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-code-block': JSXElements.StellarCodeBlockAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCodeBlockAttributes extends HTMLAttributes {
      'codeString'?: string;
      'copy'?: boolean;
      'language'?: string;
      'simple'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarCode {
      'codeString': string;
      'copy': () => void;
      'highlight': () => void;
      'language': string;
      'numbers': boolean;
      'result': () => string;
      'setCode': (code: any) => void;
    }
  }

  interface HTMLStellarCodeElement extends StencilComponents.StellarCode, HTMLStencilElement {}

  var HTMLStellarCodeElement: {
    prototype: HTMLStellarCodeElement;
    new (): HTMLStellarCodeElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-code': HTMLStellarCodeElement;
  }
  interface ElementTagNameMap {
    'stellar-code': HTMLStellarCodeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-code': JSXElements.StellarCodeAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCodeAttributes extends HTMLAttributes {
      'codeString'?: string;
      'language'?: string;
      'numbers'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarColorLibrary {

    }
  }

  interface HTMLStellarColorLibraryElement extends StencilComponents.StellarColorLibrary, HTMLStencilElement {}

  var HTMLStellarColorLibraryElement: {
    prototype: HTMLStellarColorLibraryElement;
    new (): HTMLStellarColorLibraryElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-color-library': HTMLStellarColorLibraryElement;
  }
  interface ElementTagNameMap {
    'stellar-color-library': HTMLStellarColorLibraryElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-color-library': JSXElements.StellarColorLibraryAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarColorLibraryAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarColorPicker {
      'value': string;
    }
  }

  interface HTMLStellarColorPickerElement extends StencilComponents.StellarColorPicker, HTMLStencilElement {}

  var HTMLStellarColorPickerElement: {
    prototype: HTMLStellarColorPickerElement;
    new (): HTMLStellarColorPickerElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-color-picker': HTMLStellarColorPickerElement;
  }
  interface ElementTagNameMap {
    'stellar-color-picker': HTMLStellarColorPickerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-color-picker': JSXElements.StellarColorPickerAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarColorPickerAttributes extends HTMLAttributes {
      'onColorChanged'?: (event: CustomEvent) => void;
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarComment {
      'content': string;
    }
  }

  interface HTMLStellarCommentElement extends StencilComponents.StellarComment, HTMLStencilElement {}

  var HTMLStellarCommentElement: {
    prototype: HTMLStellarCommentElement;
    new (): HTMLStellarCommentElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-comment': HTMLStellarCommentElement;
  }
  interface ElementTagNameMap {
    'stellar-comment': HTMLStellarCommentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-comment': JSXElements.StellarCommentAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCommentAttributes extends HTMLAttributes {
      'content'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarComments {

    }
  }

  interface HTMLStellarCommentsElement extends StencilComponents.StellarComments, HTMLStencilElement {}

  var HTMLStellarCommentsElement: {
    prototype: HTMLStellarCommentsElement;
    new (): HTMLStellarCommentsElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-comments': HTMLStellarCommentsElement;
  }
  interface ElementTagNameMap {
    'stellar-comments': HTMLStellarCommentsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-comments': JSXElements.StellarCommentsAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarCommentsAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarContent {
      'for': string;
      'name': string;
      'open': boolean;
    }
  }

  interface HTMLStellarContentElement extends StencilComponents.StellarContent, HTMLStencilElement {}

  var HTMLStellarContentElement: {
    prototype: HTMLStellarContentElement;
    new (): HTMLStellarContentElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-content': HTMLStellarContentElement;
  }
  interface ElementTagNameMap {
    'stellar-content': HTMLStellarContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-content': JSXElements.StellarContentAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarContentAttributes extends HTMLAttributes {
      'for'?: string;
      'name'?: string;
      'open'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface CopyWrap {
      'align': string;
      'full': boolean;
    }
  }

  interface HTMLCopyWrapElement extends StencilComponents.CopyWrap, HTMLStencilElement {}

  var HTMLCopyWrapElement: {
    prototype: HTMLCopyWrapElement;
    new (): HTMLCopyWrapElement;
  };
  interface HTMLElementTagNameMap {
    'copy-wrap': HTMLCopyWrapElement;
  }
  interface ElementTagNameMap {
    'copy-wrap': HTMLCopyWrapElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'copy-wrap': JSXElements.CopyWrapAttributes;
    }
  }
  namespace JSXElements {
    export interface CopyWrapAttributes extends HTMLAttributes {
      'align'?: string;
      'full'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarDocumentationSite {

    }
  }

  interface HTMLStellarDocumentationSiteElement extends StencilComponents.StellarDocumentationSite, HTMLStencilElement {}

  var HTMLStellarDocumentationSiteElement: {
    prototype: HTMLStellarDocumentationSiteElement;
    new (): HTMLStellarDocumentationSiteElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-documentation-site': HTMLStellarDocumentationSiteElement;
  }
  interface ElementTagNameMap {
    'stellar-documentation-site': HTMLStellarDocumentationSiteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-documentation-site': JSXElements.StellarDocumentationSiteAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarDocumentationSiteAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarDocumentation {
      'codeString': string;
      'preview': boolean;
      'reload': () => void;
      'subtitle': string;
      'title': string;
      'type': string;
    }
  }

  interface HTMLStellarDocumentationElement extends StencilComponents.StellarDocumentation, HTMLStencilElement {}

  var HTMLStellarDocumentationElement: {
    prototype: HTMLStellarDocumentationElement;
    new (): HTMLStellarDocumentationElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-documentation': HTMLStellarDocumentationElement;
  }
  interface ElementTagNameMap {
    'stellar-documentation': HTMLStellarDocumentationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-documentation': JSXElements.StellarDocumentationAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarDocumentationAttributes extends HTMLAttributes {
      'codeString'?: string;
      'preview'?: boolean;
      'subtitle'?: string;
      'title'?: string;
      'type'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarDropdown {
      'icon': boolean;
      'label': string;
      'open': boolean;
      'position': "left"|"center"|"right";
    }
  }

  interface HTMLStellarDropdownElement extends StencilComponents.StellarDropdown, HTMLStencilElement {}

  var HTMLStellarDropdownElement: {
    prototype: HTMLStellarDropdownElement;
    new (): HTMLStellarDropdownElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-dropdown': HTMLStellarDropdownElement;
  }
  interface ElementTagNameMap {
    'stellar-dropdown': HTMLStellarDropdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-dropdown': JSXElements.StellarDropdownAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarDropdownAttributes extends HTMLAttributes {
      'icon'?: boolean;
      'label'?: string;
      'open'?: boolean;
      'position'?: "left"|"center"|"right";
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarFooter {

    }
  }

  interface HTMLStellarFooterElement extends StencilComponents.StellarFooter, HTMLStencilElement {}

  var HTMLStellarFooterElement: {
    prototype: HTMLStellarFooterElement;
    new (): HTMLStellarFooterElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-footer': HTMLStellarFooterElement;
  }
  interface ElementTagNameMap {
    'stellar-footer': HTMLStellarFooterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-footer': JSXElements.StellarFooterAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarFooterAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarForm {
      'acceptCharset': string;
      'action': string;
      'ajax': boolean;
      'autocomplete': string;
      'enctype': string;
      'method': string;
      'name': string;
      'novalidate': boolean;
      'refresh': () => void;
      'submit': () => void;
      'target': string;
    }
  }

  interface HTMLStellarFormElement extends StencilComponents.StellarForm, HTMLStencilElement {}

  var HTMLStellarFormElement: {
    prototype: HTMLStellarFormElement;
    new (): HTMLStellarFormElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-form': HTMLStellarFormElement;
  }
  interface ElementTagNameMap {
    'stellar-form': HTMLStellarFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-form': JSXElements.StellarFormAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarFormAttributes extends HTMLAttributes {
      'acceptCharset'?: string;
      'action'?: string;
      'ajax'?: boolean;
      'autocomplete'?: string;
      'enctype'?: string;
      'method'?: string;
      'name'?: string;
      'novalidate'?: boolean;
      'target'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarGrid {
      'align': string;
      'cols': number|string;
      'compact': boolean;
      'padding': boolean;
      'refresh': () => void;
      'responsive': boolean;
    }
  }

  interface HTMLStellarGridElement extends StencilComponents.StellarGrid, HTMLStencilElement {}

  var HTMLStellarGridElement: {
    prototype: HTMLStellarGridElement;
    new (): HTMLStellarGridElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-grid': HTMLStellarGridElement;
  }
  interface ElementTagNameMap {
    'stellar-grid': HTMLStellarGridElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-grid': JSXElements.StellarGridAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarGridAttributes extends HTMLAttributes {
      'align'?: string;
      'cols'?: number|string;
      'compact'?: boolean;
      'padding'?: boolean;
      'responsive'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarGroupOverflow {
      'count': number;
      'size': string;
    }
  }

  interface HTMLStellarGroupOverflowElement extends StencilComponents.StellarGroupOverflow, HTMLStencilElement {}

  var HTMLStellarGroupOverflowElement: {
    prototype: HTMLStellarGroupOverflowElement;
    new (): HTMLStellarGroupOverflowElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-group-overflow': HTMLStellarGroupOverflowElement;
  }
  interface ElementTagNameMap {
    'stellar-group-overflow': HTMLStellarGroupOverflowElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-group-overflow': JSXElements.StellarGroupOverflowAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarGroupOverflowAttributes extends HTMLAttributes {
      'count'?: number;
      'size'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarGroup {
      'count': number;
      'overflow': boolean;
      'size': string;
    }
  }

  interface HTMLStellarGroupElement extends StencilComponents.StellarGroup, HTMLStencilElement {}

  var HTMLStellarGroupElement: {
    prototype: HTMLStellarGroupElement;
    new (): HTMLStellarGroupElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-group': HTMLStellarGroupElement;
  }
  interface ElementTagNameMap {
    'stellar-group': HTMLStellarGroupElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-group': JSXElements.StellarGroupAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarGroupAttributes extends HTMLAttributes {
      'count'?: number;
      'overflow'?: boolean;
      'size'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarHeader {
      'invert': boolean;
      'mark': string;
      'max': number;
      'value': number;
    }
  }

  interface HTMLStellarHeaderElement extends StencilComponents.StellarHeader, HTMLStencilElement {}

  var HTMLStellarHeaderElement: {
    prototype: HTMLStellarHeaderElement;
    new (): HTMLStellarHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-header': HTMLStellarHeaderElement;
  }
  interface ElementTagNameMap {
    'stellar-header': HTMLStellarHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-header': JSXElements.StellarHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarHeaderAttributes extends HTMLAttributes {
      'invert'?: boolean;
      'mark'?: string;
      'max'?: number;
      'value'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarImage {
      'bg': string;
      'height': number;
      'medium': () => any;
      'preload': string;
      'width': number;
    }
  }

  interface HTMLStellarImageElement extends StencilComponents.StellarImage, HTMLStencilElement {}

  var HTMLStellarImageElement: {
    prototype: HTMLStellarImageElement;
    new (): HTMLStellarImageElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-image': HTMLStellarImageElement;
  }
  interface ElementTagNameMap {
    'stellar-image': HTMLStellarImageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-image': JSXElements.StellarImageAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarImageAttributes extends HTMLAttributes {
      'bg'?: string;
      'height'?: number;
      'preload'?: string;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarInput {
      'autocomplete': string;
      'autofocus': boolean;
      'color': string;
      'cols': number;
      'disabled': boolean;
      'focused': boolean;
      'getStrength': () => object;
      'invalid': (message: string | boolean, valid?: boolean, level?: number) => void;
      'label': string;
      'match': string;
      'max': number;
      'maxlength': number;
      'min': number;
      /**
       * The name of the input element
       */
      'name': string;
      'novalidation': boolean;
      'placeholder': string;
      'readonly': boolean;
      'required': boolean;
      'rows': number;
      'setStrength': (value: number) => void;
      'size': string;
      'spellcheck': boolean;
      'step': number;
      /**
       * The kind of element that the Input should be rendered as
       */
      'type': string;
      'val': () => any;
      'validate': () => { errors?: any; valid?: boolean; level?: number; };
      'validates': string;
      /**
       * The pre-set value to pass to the input element
       */
      'value': any;
      'wrap': string;
    }
  }

  interface HTMLStellarInputElement extends StencilComponents.StellarInput, HTMLStencilElement {}

  var HTMLStellarInputElement: {
    prototype: HTMLStellarInputElement;
    new (): HTMLStellarInputElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-input': HTMLStellarInputElement;
  }
  interface ElementTagNameMap {
    'stellar-input': HTMLStellarInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-input': JSXElements.StellarInputAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarInputAttributes extends HTMLAttributes {
      'autocomplete'?: string;
      'autofocus'?: boolean;
      'color'?: string;
      'cols'?: number;
      'disabled'?: boolean;
      'focused'?: boolean;
      'label'?: string;
      'match'?: string;
      'max'?: number;
      'maxlength'?: number;
      'min'?: number;
      /**
       * The name of the input element
       */
      'name'?: string;
      'novalidation'?: boolean;
      /**
       * Public: Changed event
       */
      'onValueChanged'?: (event: CustomEvent) => void;
      'placeholder'?: string;
      'readonly'?: boolean;
      'required'?: boolean;
      'rows'?: number;
      'size'?: string;
      'spellcheck'?: boolean;
      'step'?: number;
      /**
       * The kind of element that the Input should be rendered as
       */
      'type'?: string;
      'validates'?: string;
      /**
       * The pre-set value to pass to the input element
       */
      'value'?: any;
      'wrap'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarItem {
      'apply': (data: any) => void;
      'danger': boolean;
      'data': () => { size: string; value: string; type: "button" | "a"; label: string; danger: boolean; slotted: any; };
      'fit': boolean;
      'focus': () => void;
      'focused': boolean;
      'href': string;
      'label': string;
      'selectable': boolean;
      'selected': boolean;
      'size': string;
      'type': "a"|"button";
      'value': string;
    }
  }

  interface HTMLStellarItemElement extends StencilComponents.StellarItem, HTMLStencilElement {}

  var HTMLStellarItemElement: {
    prototype: HTMLStellarItemElement;
    new (): HTMLStellarItemElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-item': HTMLStellarItemElement;
  }
  interface ElementTagNameMap {
    'stellar-item': HTMLStellarItemElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-item': JSXElements.StellarItemAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarItemAttributes extends HTMLAttributes {
      'danger'?: boolean;
      'fit'?: boolean;
      'focused'?: boolean;
      'href'?: string;
      'label'?: string;
      'onBlurChanged'?: (event: CustomEvent) => void;
      'onFocusChanged'?: (event: CustomEvent) => void;
      'onSelectionChanged'?: (event: CustomEvent) => void;
      'selectable'?: boolean;
      'selected'?: boolean;
      'size'?: string;
      'type'?: "a"|"button";
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarLabel {
      'for': string;
    }
  }

  interface HTMLStellarLabelElement extends StencilComponents.StellarLabel, HTMLStencilElement {}

  var HTMLStellarLabelElement: {
    prototype: HTMLStellarLabelElement;
    new (): HTMLStellarLabelElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-label': HTMLStellarLabelElement;
  }
  interface ElementTagNameMap {
    'stellar-label': HTMLStellarLabelElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-label': JSXElements.StellarLabelAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarLabelAttributes extends HTMLAttributes {
      'for'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarLayout {
      'align': "baseline"|"center"|"top"|"bottom";
      'padding': "tiny"|"small"|"medium"|"large";
      'refresh': () => void;
      'size': "tiny"|"small"|"medium"|"large"|"full"|"flush";
      'type': string;
    }
  }

  interface HTMLStellarLayoutElement extends StencilComponents.StellarLayout, HTMLStencilElement {}

  var HTMLStellarLayoutElement: {
    prototype: HTMLStellarLayoutElement;
    new (): HTMLStellarLayoutElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-layout': HTMLStellarLayoutElement;
  }
  interface ElementTagNameMap {
    'stellar-layout': HTMLStellarLayoutElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-layout': JSXElements.StellarLayoutAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarLayoutAttributes extends HTMLAttributes {
      'align'?: "baseline"|"center"|"top"|"bottom";
      'padding'?: "tiny"|"small"|"medium"|"large";
      'size'?: "tiny"|"small"|"medium"|"large"|"full"|"flush";
      'type'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarList {
      'append': (value: any) => void;
      'itemHeight': number;
      'items': Array<any>;
      'mount': () => void;
      'prepend': (value: any) => void;
      'refresh': () => void;
      'updateConfig': (config: any) => void;
    }
  }

  interface HTMLStellarListElement extends StencilComponents.StellarList, HTMLStencilElement {}

  var HTMLStellarListElement: {
    prototype: HTMLStellarListElement;
    new (): HTMLStellarListElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-list': HTMLStellarListElement;
  }
  interface ElementTagNameMap {
    'stellar-list': HTMLStellarListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-list': JSXElements.StellarListAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarListAttributes extends HTMLAttributes {
      'itemHeight'?: number;
      'items'?: Array<any>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarMarkdown {
      'src': string;
    }
  }

  interface HTMLStellarMarkdownElement extends StencilComponents.StellarMarkdown, HTMLStencilElement {}

  var HTMLStellarMarkdownElement: {
    prototype: HTMLStellarMarkdownElement;
    new (): HTMLStellarMarkdownElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-markdown': HTMLStellarMarkdownElement;
  }
  interface ElementTagNameMap {
    'stellar-markdown': HTMLStellarMarkdownElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-markdown': JSXElements.StellarMarkdownAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarMarkdownAttributes extends HTMLAttributes {
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarMessage {
      'closable': boolean;
      'name': string;
      'remember': boolean;
      'size': "full"|"default";
      'striped': boolean;
      'type': "alert"|"error"|"info"|"success";
      'visible': boolean;
    }
  }

  interface HTMLStellarMessageElement extends StencilComponents.StellarMessage, HTMLStencilElement {}

  var HTMLStellarMessageElement: {
    prototype: HTMLStellarMessageElement;
    new (): HTMLStellarMessageElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-message': HTMLStellarMessageElement;
  }
  interface ElementTagNameMap {
    'stellar-message': HTMLStellarMessageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-message': JSXElements.StellarMessageAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarMessageAttributes extends HTMLAttributes {
      'closable'?: boolean;
      'name'?: string;
      'remember'?: boolean;
      'size'?: "full"|"default";
      'striped'?: boolean;
      'type'?: "alert"|"error"|"info"|"success";
      'visible'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarModalController {
      'close': () => Promise<boolean>;
      'open': (modalName: any, originalContent: any) => Promise<boolean>;
      'size': string;
      'state': string|"opening"|"open"|"closing"|"closed"|"empty";
      'timing': number;
    }
  }

  interface HTMLStellarModalControllerElement extends StencilComponents.StellarModalController, HTMLStencilElement {}

  var HTMLStellarModalControllerElement: {
    prototype: HTMLStellarModalControllerElement;
    new (): HTMLStellarModalControllerElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-modal-controller': HTMLStellarModalControllerElement;
  }
  interface ElementTagNameMap {
    'stellar-modal-controller': HTMLStellarModalControllerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-modal-controller': JSXElements.StellarModalControllerAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarModalControllerAttributes extends HTMLAttributes {
      'size'?: string;
      'state'?: string|"opening"|"open"|"closing"|"closed"|"empty";
      'timing'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarModal {
      'active': boolean;
      'cloned': boolean;
      'close': () => boolean;
      'header': boolean;
      'name': string;
      'open': () => boolean;
      'size': string;
    }
  }

  interface HTMLStellarModalElement extends StencilComponents.StellarModal, HTMLStencilElement {}

  var HTMLStellarModalElement: {
    prototype: HTMLStellarModalElement;
    new (): HTMLStellarModalElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-modal': HTMLStellarModalElement;
  }
  interface ElementTagNameMap {
    'stellar-modal': HTMLStellarModalElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-modal': JSXElements.StellarModalAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarModalAttributes extends HTMLAttributes {
      'active'?: boolean;
      'cloned'?: boolean;
      'header'?: boolean;
      'name'?: string;
      'size'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarOverlay {
      'open': boolean;
    }
  }

  interface HTMLStellarOverlayElement extends StencilComponents.StellarOverlay, HTMLStencilElement {}

  var HTMLStellarOverlayElement: {
    prototype: HTMLStellarOverlayElement;
    new (): HTMLStellarOverlayElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-overlay': HTMLStellarOverlayElement;
  }
  interface ElementTagNameMap {
    'stellar-overlay': HTMLStellarOverlayElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-overlay': JSXElements.StellarOverlayAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarOverlayAttributes extends HTMLAttributes {
      'open'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarPagination {
      'color': string;
      'current': number;
      'padding': number;
      /**
       * Public: Sets the max cap of pages you can skip through
       */
      'pages': number;
      'skip': boolean;
      'type': "full"|"compact";
      'url': any;
    }
  }

  interface HTMLStellarPaginationElement extends StencilComponents.StellarPagination, HTMLStencilElement {}

  var HTMLStellarPaginationElement: {
    prototype: HTMLStellarPaginationElement;
    new (): HTMLStellarPaginationElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-pagination': HTMLStellarPaginationElement;
  }
  interface ElementTagNameMap {
    'stellar-pagination': HTMLStellarPaginationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-pagination': JSXElements.StellarPaginationAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarPaginationAttributes extends HTMLAttributes {
      'color'?: string;
      'current'?: number;
      'onChanged'?: (event: CustomEvent) => void;
      'padding'?: number;
      /**
       * Public: Sets the max cap of pages you can skip through
       */
      'pages'?: number;
      'skip'?: boolean;
      'type'?: "full"|"compact";
      'url'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarParallaxSection {
      'layer': number;
      'percentage': number;
      'speed': number;
    }
  }

  interface HTMLStellarParallaxSectionElement extends StencilComponents.StellarParallaxSection, HTMLStencilElement {}

  var HTMLStellarParallaxSectionElement: {
    prototype: HTMLStellarParallaxSectionElement;
    new (): HTMLStellarParallaxSectionElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-parallax-section': HTMLStellarParallaxSectionElement;
  }
  interface ElementTagNameMap {
    'stellar-parallax-section': HTMLStellarParallaxSectionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-parallax-section': JSXElements.StellarParallaxSectionAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarParallaxSectionAttributes extends HTMLAttributes {
      'layer'?: number;
      'percentage'?: number;
      'speed'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarParallax {
      'reload': () => void;
    }
  }

  interface HTMLStellarParallaxElement extends StencilComponents.StellarParallax, HTMLStencilElement {}

  var HTMLStellarParallaxElement: {
    prototype: HTMLStellarParallaxElement;
    new (): HTMLStellarParallaxElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-parallax': HTMLStellarParallaxElement;
  }
  interface ElementTagNameMap {
    'stellar-parallax': HTMLStellarParallaxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-parallax': JSXElements.StellarParallaxAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarParallaxAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarProgress {
      /**
       * Sets the maximum cap for steps in the progress bar
       */
      'max': number;
      /**
       * Renders if this element is slender or not
       */
      'slender': boolean;
      /**
       * Sets the value of the progress bar
       */
      'value': number;
    }
  }

  interface HTMLStellarProgressElement extends StencilComponents.StellarProgress, HTMLStencilElement {}

  var HTMLStellarProgressElement: {
    prototype: HTMLStellarProgressElement;
    new (): HTMLStellarProgressElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-progress': HTMLStellarProgressElement;
  }
  interface ElementTagNameMap {
    'stellar-progress': HTMLStellarProgressElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-progress': JSXElements.StellarProgressAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarProgressAttributes extends HTMLAttributes {
      /**
       * Sets the maximum cap for steps in the progress bar
       */
      'max'?: number;
      /**
       * Renders if this element is slender or not
       */
      'slender'?: boolean;
      /**
       * Sets the value of the progress bar
       */
      'value'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarQuickActions {
      'open': boolean;
    }
  }

  interface HTMLStellarQuickActionsElement extends StencilComponents.StellarQuickActions, HTMLStencilElement {}

  var HTMLStellarQuickActionsElement: {
    prototype: HTMLStellarQuickActionsElement;
    new (): HTMLStellarQuickActionsElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-quick-actions': HTMLStellarQuickActionsElement;
  }
  interface ElementTagNameMap {
    'stellar-quick-actions': HTMLStellarQuickActionsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-quick-actions': JSXElements.StellarQuickActionsAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarQuickActionsAttributes extends HTMLAttributes {
      'open'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarScatter {
      'colors': boolean;
      'float': boolean;
      'max': number;
      'min': number;
      'scatter': number;
      'sizes': boolean;
    }
  }

  interface HTMLStellarScatterElement extends StencilComponents.StellarScatter, HTMLStencilElement {}

  var HTMLStellarScatterElement: {
    prototype: HTMLStellarScatterElement;
    new (): HTMLStellarScatterElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-scatter': HTMLStellarScatterElement;
  }
  interface ElementTagNameMap {
    'stellar-scatter': HTMLStellarScatterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-scatter': JSXElements.StellarScatterAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarScatterAttributes extends HTMLAttributes {
      'colors'?: boolean;
      'float'?: boolean;
      'max'?: number;
      'min'?: number;
      'scatter'?: number;
      'sizes'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarSelect {
      'focused': boolean;
      'footer': boolean;
      'inline': boolean;
      'label': string;
      'multiple': boolean;
      'name': string;
      'open': boolean;
      'other': boolean;
      'overlay': boolean;
      'placeholder': string;
      'processing': boolean;
      'required': boolean;
      'size': string;
      'validate': () => { errors?: any; valid?: boolean; level?: number; };
      'value': any;
    }
  }

  interface HTMLStellarSelectElement extends StencilComponents.StellarSelect, HTMLStencilElement {}

  var HTMLStellarSelectElement: {
    prototype: HTMLStellarSelectElement;
    new (): HTMLStellarSelectElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-select': HTMLStellarSelectElement;
  }
  interface ElementTagNameMap {
    'stellar-select': HTMLStellarSelectElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-select': JSXElements.StellarSelectAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarSelectAttributes extends HTMLAttributes {
      'focused'?: boolean;
      'footer'?: boolean;
      'inline'?: boolean;
      'label'?: string;
      'multiple'?: boolean;
      'name'?: string;
      'onChange'?: (event: CustomEvent) => void;
      'open'?: boolean;
      'other'?: boolean;
      'overlay'?: boolean;
      'placeholder'?: string;
      'processing'?: boolean;
      'required'?: boolean;
      'size'?: string;
      'value'?: any;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SkeletonImg {
      'height': number;
      'icon': boolean;
      'loading': boolean;
      'width': number;
    }
  }

  interface HTMLSkeletonImgElement extends StencilComponents.SkeletonImg, HTMLStencilElement {}

  var HTMLSkeletonImgElement: {
    prototype: HTMLSkeletonImgElement;
    new (): HTMLSkeletonImgElement;
  };
  interface HTMLElementTagNameMap {
    'skeleton-img': HTMLSkeletonImgElement;
  }
  interface ElementTagNameMap {
    'skeleton-img': HTMLSkeletonImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'skeleton-img': JSXElements.SkeletonImgAttributes;
    }
  }
  namespace JSXElements {
    export interface SkeletonImgAttributes extends HTMLAttributes {
      'height'?: number;
      'icon'?: boolean;
      'loading'?: boolean;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SkeletonText {
      'as': string|'h1'|'h2'|'h3'|'h4'|'h5'|'h6'|'p';
      'loading': boolean;
      'width': number;
    }
  }

  interface HTMLSkeletonTextElement extends StencilComponents.SkeletonText, HTMLStencilElement {}

  var HTMLSkeletonTextElement: {
    prototype: HTMLSkeletonTextElement;
    new (): HTMLSkeletonTextElement;
  };
  interface HTMLElementTagNameMap {
    'skeleton-text': HTMLSkeletonTextElement;
  }
  interface ElementTagNameMap {
    'skeleton-text': HTMLSkeletonTextElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'skeleton-text': JSXElements.SkeletonTextAttributes;
    }
  }
  namespace JSXElements {
    export interface SkeletonTextAttributes extends HTMLAttributes {
      'as'?: string|'h1'|'h2'|'h3'|'h4'|'h5'|'h6'|'p';
      'loading'?: boolean;
      'width'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarSlide {
      'motion': number;
    }
  }

  interface HTMLStellarSlideElement extends StencilComponents.StellarSlide, HTMLStencilElement {}

  var HTMLStellarSlideElement: {
    prototype: HTMLStellarSlideElement;
    new (): HTMLStellarSlideElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-slide': HTMLStellarSlideElement;
  }
  interface ElementTagNameMap {
    'stellar-slide': HTMLStellarSlideElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-slide': JSXElements.StellarSlideAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarSlideAttributes extends HTMLAttributes {
      'motion'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarSlides {
      'autoHeight': boolean;
      'centeredSlides': boolean;
      'direction': "horizontal"|"vertical";
      'effect': "slide"|"fade"|"cube"|"coverflow"|"flip";
      /**
       * Get the index of the active slide.
       */
      'getActiveIndex': () => number;
      /**
       * Get the index of the previous slide.
       */
      'getPreviousIndex': () => number;
      /**
       * Get whether or not the current slide is the first slide.
       */
      'isBeginning': () => boolean;
      /**
       * Get whether or not the current slide is the last slide.
       */
      'isEnd': () => boolean;
      /**
       * Get the total number of slides.
       */
      'length': () => number;
      /**
       * Lock or unlock the ability to slide to the next slides.
       */
      'lockSwipeToNext': (shouldLockSwipeToNext: boolean) => any;
      /**
       * Lock or unlock the ability to slide to the previous slides.
       */
      'lockSwipeToPrev': (shouldLockSwipeToPrev: boolean) => any;
      /**
       * Lock or unlock the ability to slide to change slides.
       */
      'lockSwipes': (shouldLockSwipes: boolean) => any;
      'loop': boolean;
      'nested': boolean;
      /**
       * Options to pass to the swiper instance. See http://idangero.us/swiper/api/ for valid options
       */
      'options': any;
      /**
       * Show or hide the pager
       */
      'pager': boolean;
      'pagination': boolean;
      /**
       * Transition to the next slide.
       */
      'slideNext': (speed?: number, runCallbacks?: boolean) => void;
      /**
       * Transition to the previous slide.
       */
      'slidePrev': (speed?: number, runCallbacks?: boolean) => void;
      /**
       * Transition to the specified slide.
       */
      'slideTo': (index: number, speed?: number, runCallbacks?: boolean) => void;
      'slidesPerView': number;
      'spaceBetween': number;
      'speed': number;
      /**
       * Start auto play.
       */
      'startAutoplay': () => void;
      /**
       * Stop auto play.
       */
      'stopAutoplay': () => void;
      /**
       * Update the underlying slider implementation. Call this if you've added or removed child slides.
       */
      'update': () => void;
      'watchSlidesProgress': boolean;
      'watchSlidesVisibility': boolean;
    }
  }

  interface HTMLStellarSlidesElement extends StencilComponents.StellarSlides, HTMLStencilElement {}

  var HTMLStellarSlidesElement: {
    prototype: HTMLStellarSlidesElement;
    new (): HTMLStellarSlidesElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-slides': HTMLStellarSlidesElement;
  }
  interface ElementTagNameMap {
    'stellar-slides': HTMLStellarSlidesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-slides': JSXElements.StellarSlidesAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarSlidesAttributes extends HTMLAttributes {
      'autoHeight'?: boolean;
      'centeredSlides'?: boolean;
      'direction'?: "horizontal"|"vertical";
      'effect'?: "slide"|"fade"|"cube"|"coverflow"|"flip";
      'loop'?: boolean;
      'nested'?: boolean;
      /**
       * Emitted after the active slide has changed.
       */
      'onIonSlideDidChange'?: (event: CustomEvent) => void;
      /**
       * Emitted when the slider is actively being moved.
       */
      'onIonSlideDrag'?: (event: CustomEvent) => void;
      /**
       * Emitted when the next slide has ended.
       */
      'onIonSlideNextEnd'?: (event: CustomEvent) => void;
      /**
       * Emitted when the next slide has started.
       */
      'onIonSlideNextStart'?: (event: CustomEvent) => void;
      /**
       * Emitted when the previous slide has ended.
       */
      'onIonSlidePrevEnd'?: (event: CustomEvent) => void;
      /**
       * Emitted when the previous slide has started.
       */
      'onIonSlidePrevStart'?: (event: CustomEvent) => void;
      /**
       * Emitted when the slider is at the last slide.
       */
      'onIonSlideReachEnd'?: (event: CustomEvent) => void;
      /**
       * Emitted when the slider is at its initial position.
       */
      'onIonSlideReachStart'?: (event: CustomEvent) => void;
      /**
       * Emitted when the user releases the touch.
       */
      'onIonSlideTouchEnd'?: (event: CustomEvent) => void;
      /**
       * Emitted when the user first touches the slider.
       */
      'onIonSlideTouchStart'?: (event: CustomEvent) => void;
      /**
       * Emitted when the slide transition has ended.
       */
      'onIonSlideTransitionEnd'?: (event: CustomEvent) => void;
      /**
       * Emitted when the slide transition has started.
       */
      'onIonSlideTransitionStart'?: (event: CustomEvent) => void;
      /**
       * Emitted before the active slide has changed.
       */
      'onIonSlideWillChange'?: (event: CustomEvent) => void;
      /**
       * Options to pass to the swiper instance. See http://idangero.us/swiper/api/ for valid options
       */
      'options'?: any;
      /**
       * Show or hide the pager
       */
      'pager'?: boolean;
      'pagination'?: boolean;
      'slidesPerView'?: number;
      'spaceBetween'?: number;
      'speed'?: number;
      'watchSlidesProgress'?: boolean;
      'watchSlidesVisibility'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarStarscape {

    }
  }

  interface HTMLStellarStarscapeElement extends StencilComponents.StellarStarscape, HTMLStencilElement {}

  var HTMLStellarStarscapeElement: {
    prototype: HTMLStellarStarscapeElement;
    new (): HTMLStellarStarscapeElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-starscape': HTMLStellarStarscapeElement;
  }
  interface ElementTagNameMap {
    'stellar-starscape': HTMLStellarStarscapeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-starscape': JSXElements.StellarStarscapeAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarStarscapeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarStep {
      'disabled': boolean;
      'href': string;
      'open': boolean;
    }
  }

  interface HTMLStellarStepElement extends StencilComponents.StellarStep, HTMLStencilElement {}

  var HTMLStellarStepElement: {
    prototype: HTMLStellarStepElement;
    new (): HTMLStellarStepElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-step': HTMLStellarStepElement;
  }
  interface ElementTagNameMap {
    'stellar-step': HTMLStellarStepElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-step': JSXElements.StellarStepAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarStepAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'href'?: string;
      'onContentChange'?: (event: CustomEvent) => void;
      'open'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarSteps {
      'contents': () => NodeListOf<any>;
      'name': string;
      'steps': () => NodeListOf<any>;
    }
  }

  interface HTMLStellarStepsElement extends StencilComponents.StellarSteps, HTMLStencilElement {}

  var HTMLStellarStepsElement: {
    prototype: HTMLStellarStepsElement;
    new (): HTMLStellarStepsElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-steps': HTMLStellarStepsElement;
  }
  interface ElementTagNameMap {
    'stellar-steps': HTMLStellarStepsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-steps': JSXElements.StellarStepsAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarStepsAttributes extends HTMLAttributes {
      'name'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarStripe {
      'connect': () => void;
      'getToken': () => Promise<boolean>;
      'name': string;
      'setError': (error: string) => void;
      'token': string;
    }
  }

  interface HTMLStellarStripeElement extends StencilComponents.StellarStripe, HTMLStencilElement {}

  var HTMLStellarStripeElement: {
    prototype: HTMLStellarStripeElement;
    new (): HTMLStellarStripeElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-stripe': HTMLStellarStripeElement;
  }
  interface ElementTagNameMap {
    'stellar-stripe': HTMLStellarStripeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-stripe': JSXElements.StellarStripeAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarStripeAttributes extends HTMLAttributes {
      'name'?: string;
      'token'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarSwitch {
      'checked': boolean;
    }
  }

  interface HTMLStellarSwitchElement extends StencilComponents.StellarSwitch, HTMLStencilElement {}

  var HTMLStellarSwitchElement: {
    prototype: HTMLStellarSwitchElement;
    new (): HTMLStellarSwitchElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-switch': HTMLStellarSwitchElement;
  }
  interface ElementTagNameMap {
    'stellar-switch': HTMLStellarSwitchElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-switch': JSXElements.StellarSwitchAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarSwitchAttributes extends HTMLAttributes {
      'checked'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarTab {
      'disabled': boolean;
      'href': string;
      'notifications': boolean|number;
      'open': boolean;
      'tag': string;
    }
  }

  interface HTMLStellarTabElement extends StencilComponents.StellarTab, HTMLStencilElement {}

  var HTMLStellarTabElement: {
    prototype: HTMLStellarTabElement;
    new (): HTMLStellarTabElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-tab': HTMLStellarTabElement;
  }
  interface ElementTagNameMap {
    'stellar-tab': HTMLStellarTabElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-tab': JSXElements.StellarTabAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarTabAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'href'?: string;
      'notifications'?: boolean|number;
      'onContentChange'?: (event: CustomEvent) => void;
      'open'?: boolean;
      'tag'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarTable {
      'chart': boolean;
      'name': string;
      'striped': boolean;
      'upgrade': boolean;
    }
  }

  interface HTMLStellarTableElement extends StencilComponents.StellarTable, HTMLStencilElement {}

  var HTMLStellarTableElement: {
    prototype: HTMLStellarTableElement;
    new (): HTMLStellarTableElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-table': HTMLStellarTableElement;
  }
  interface ElementTagNameMap {
    'stellar-table': HTMLStellarTableElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-table': JSXElements.StellarTableAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarTableAttributes extends HTMLAttributes {
      'chart'?: boolean;
      'name'?: string;
      'striped'?: boolean;
      'upgrade'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarTabs {
      'block': boolean;
      'blurring': number;
      'contents': () => NodeListOf<any>;
      'height': string;
      'name': string;
      'noanimation': boolean;
      'tabs': () => NodeListOf<any>;
    }
  }

  interface HTMLStellarTabsElement extends StencilComponents.StellarTabs, HTMLStencilElement {}

  var HTMLStellarTabsElement: {
    prototype: HTMLStellarTabsElement;
    new (): HTMLStellarTabsElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-tabs': HTMLStellarTabsElement;
  }
  interface ElementTagNameMap {
    'stellar-tabs': HTMLStellarTabsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-tabs': JSXElements.StellarTabsAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarTabsAttributes extends HTMLAttributes {
      'block'?: boolean;
      'blurring'?: number;
      'height'?: string;
      'name'?: string;
      'noanimation'?: boolean;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarTag {
      'color': string;
      'outline': boolean;
      'pill': boolean;
      'size': string;
      'textColor': string;
    }
  }

  interface HTMLStellarTagElement extends StencilComponents.StellarTag, HTMLStencilElement {}

  var HTMLStellarTagElement: {
    prototype: HTMLStellarTagElement;
    new (): HTMLStellarTagElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-tag': HTMLStellarTagElement;
  }
  interface ElementTagNameMap {
    'stellar-tag': HTMLStellarTagElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-tag': JSXElements.StellarTagAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarTagAttributes extends HTMLAttributes {
      'color'?: string;
      'outline'?: boolean;
      'pill'?: boolean;
      'size'?: string;
      'textColor'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarThemePreview {
      'base': string;
      'complement': string;
    }
  }

  interface HTMLStellarThemePreviewElement extends StencilComponents.StellarThemePreview, HTMLStencilElement {}

  var HTMLStellarThemePreviewElement: {
    prototype: HTMLStellarThemePreviewElement;
    new (): HTMLStellarThemePreviewElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-theme-preview': HTMLStellarThemePreviewElement;
  }
  interface ElementTagNameMap {
    'stellar-theme-preview': HTMLStellarThemePreviewElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-theme-preview': JSXElements.StellarThemePreviewAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarThemePreviewAttributes extends HTMLAttributes {
      'base'?: string;
      'complement'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarToggleOption {
      'checked': boolean;
      'default': string;
      'for': string;
      'icon': boolean;
      'inline': boolean;
      'name': string;
      'required': boolean;
      'selectedCopy': string;
      'single': boolean;
      'size': boolean;
      'type': string;
      'updateSelected': (value: boolean) => void;
      'value': string;
    }
  }

  interface HTMLStellarToggleOptionElement extends StencilComponents.StellarToggleOption, HTMLStencilElement {}

  var HTMLStellarToggleOptionElement: {
    prototype: HTMLStellarToggleOptionElement;
    new (): HTMLStellarToggleOptionElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-toggle-option': HTMLStellarToggleOptionElement;
  }
  interface ElementTagNameMap {
    'stellar-toggle-option': HTMLStellarToggleOptionElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-toggle-option': JSXElements.StellarToggleOptionAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarToggleOptionAttributes extends HTMLAttributes {
      'checked'?: boolean;
      'default'?: string;
      'for'?: string;
      'icon'?: boolean;
      'inline'?: boolean;
      'name'?: string;
      'onToggleChanged'?: (event: CustomEvent) => void;
      'required'?: boolean;
      'selectedCopy'?: string;
      'single'?: boolean;
      'size'?: boolean;
      'type'?: string;
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarToggle {
      'card': string;
      'flip': boolean;
      'label': string;
      'name': string;
      'required': boolean;
      'single': boolean;
      'size': string;
      'stacked': boolean;
      'type': string|"checkbox"|"radio"|"radio-block"|"checkbox-block";
      'value': string;
    }
  }

  interface HTMLStellarToggleElement extends StencilComponents.StellarToggle, HTMLStencilElement {}

  var HTMLStellarToggleElement: {
    prototype: HTMLStellarToggleElement;
    new (): HTMLStellarToggleElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-toggle': HTMLStellarToggleElement;
  }
  interface ElementTagNameMap {
    'stellar-toggle': HTMLStellarToggleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-toggle': JSXElements.StellarToggleAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarToggleAttributes extends HTMLAttributes {
      'card'?: string;
      'flip'?: boolean;
      'label'?: string;
      'name'?: string;
      'required'?: boolean;
      'single'?: boolean;
      'size'?: string;
      'stacked'?: boolean;
      'type'?: string|"checkbox"|"radio"|"radio-block"|"checkbox-block";
      'value'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarTooltip {
      'align': "left"|"center"|"right";
    }
  }

  interface HTMLStellarTooltipElement extends StencilComponents.StellarTooltip, HTMLStencilElement {}

  var HTMLStellarTooltipElement: {
    prototype: HTMLStellarTooltipElement;
    new (): HTMLStellarTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-tooltip': HTMLStellarTooltipElement;
  }
  interface ElementTagNameMap {
    'stellar-tooltip': HTMLStellarTooltipElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-tooltip': JSXElements.StellarTooltipAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarTooltipAttributes extends HTMLAttributes {
      'align'?: "left"|"center"|"right";
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarUnit {
      'decimals': number;
      'from': string;
      'round': boolean;
      'to': string;
      'value': number;
    }
  }

  interface HTMLStellarUnitElement extends StencilComponents.StellarUnit, HTMLStencilElement {}

  var HTMLStellarUnitElement: {
    prototype: HTMLStellarUnitElement;
    new (): HTMLStellarUnitElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-unit': HTMLStellarUnitElement;
  }
  interface ElementTagNameMap {
    'stellar-unit': HTMLStellarUnitElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-unit': JSXElements.StellarUnitAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarUnitAttributes extends HTMLAttributes {
      'decimals'?: number;
      'from'?: string;
      'round'?: boolean;
      'to'?: string;
      'value'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface StellarVideo {
      'autoplay': boolean;
      'height': number;
      'muted': boolean;
      'playsinline': boolean;
      'poster': string;
      'preload': string;
      'width': number;
    }
  }

  interface HTMLStellarVideoElement extends StencilComponents.StellarVideo, HTMLStencilElement {}

  var HTMLStellarVideoElement: {
    prototype: HTMLStellarVideoElement;
    new (): HTMLStellarVideoElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-video': HTMLStellarVideoElement;
  }
  interface ElementTagNameMap {
    'stellar-video': HTMLStellarVideoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stellar-video': JSXElements.StellarVideoAttributes;
    }
  }
  namespace JSXElements {
    export interface StellarVideoAttributes extends HTMLAttributes {
      'autoplay'?: boolean;
      'height'?: number;
      'muted'?: boolean;
      'playsinline'?: boolean;
      'poster'?: string;
      'preload'?: string;
      'width'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;